### ISSUE TITLE
ApplicationVariant in AppExtension:applicationVariants is not a link

### ISSUE THREAD

**Issue by koral--** [google/android-gradle-dsl#3]
ApplicationVariant is gray and not clickable as shown in attachment.
![image](https://cloud.githubusercontent.com/assets/3340954/15246872/68c14fd4-1910-11e6-8088-fc1ca4c23e1b.png)

Here is a location:
http://google.github.io/android-gradle-dsl/current/com.android.build.gradle.AppExtension.html#com.android.build.gradle.AppExtension:applicationVariants

**Comment by benol** [comment]
Thanks for the report - we're aware of the issue and I'm looking at publishing proper docs for the whole "Variants API" interface.

**Comment by arrogant-gandroid-team** [comment]
@koral-- 

It seems you're new to Android programming?

Ambiguous documentation is Google's Android team tattoo. They're so proud of it.

I really recommend you dig the source code yourself. Hint: you can see the last comment was from May, now is August. I'm right, right? Get familiar with Android programming, you will see more and more ambiguous documentation which have been there for years, since 2007. The first Android guys have left Google since Apple revealed the first iPhone. So no one is gonna update ambiguous documentation.

They're so proud of it.

**Comment by jfirebaugh** [comment]
Same with [`libraryVariants`/`LibraryVariant`](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.LibraryExtension.html#com.android.build.gradle.LibraryExtension:libraryVariants).

**Comment by gavra0** [comment]
Please file bugs at https://issuetracker.google.com/issues/new?component=192708&template=840533. There is more information about the process here: https://developer.android.com/studio/report-bugs.
